#! /bin/bash

host="${USER}@login.mpip-mainz.mpg.de"
repobase="hgrepos"

die() {
  echo "$*" >&2
  exit 1
}

if [ -z "$1" ]; then
   $0 --help
   exit 0
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   cat <<EOF
Usage: ${0##*/} push|pull|clone|cloneto [name]

This is wrapper to handle hg repos at ${host}.
Subfuolder is $repobase.

Operations: 
push          push changes to $host
pull          pull changes from $host
clone         clone repo from $host
cloneto       clone repo to $host
EOF
   exit 0
fi

if [ "$1" = "cloneto" ]; then
   op="clone ."
else
   op=$1
fi

if [ "$op" = "clone" ]; then
   [[ -n "$2" ]] || die "clone needs a name"
else
   path=$(hg root) || die "Could not get (hg root) dir"
   cd $path
fi
  
if [ -n "$2" ]; then
   name=$2
else
   name=${path##*/}
fi
   
echo Reponame: $name
echo Operation: $1

hg $op ssh://$host/$repobase/$name
